export default {
  // CRUD actions
  GET_CAMPUS: "GET_CAMPUS",
  GET_ALL_CAMPUS: "GET_ALL_CAMPUS",
  ADD_CAMPUS: "ADD_CAMPUS",
  UPDATE_CAMPUS: "UPDATE_CAMPUS",
  DELETE_CAMPUS: "DELETE_CAMPUS",

  // YOUR actions
  COUNTDUX: "COUNTDUX",
  MIGRATEDUX: "MIGRATEDUX",
  QUACKONE: "QUACKONE"
};
