export default {
	// CRUD actions
	GET_TERMINATOR : 'GET_TERMINATOR',
	GET_ALL_TERMINATOR : 'GET_ALL_TERMINATOR',
	ADD_TERMINATOR : 'ADD_TERMINATOR',
	UPDATE_TERMINATOR : 'UPDATE_TERMINATOR',
	DELETE_TERMINATOR : 'DELETE_TERMINATOR',

	// YOUR actions 
	COUNTDUX : 'COUNTDUX',
	MIGRATEDUX : 'MIGRATEDUX',
	QUACKONE : 'QUACKONE',
	KILLJOHNCONNOR : 'KILLJOHNCONNOR',
	BACKINTIME : 'BACKINTIME',
}