export const GET_ALL_CAMPUS = "GET_ALL_CAMPUS";
export const ADD_CAMPUS = "ADD_CAMPUS";

export default {
  GET_CAMPUS: "GET_CAMPUS",
  GET_ALL_CAMPUS: "GET_ALL_CAMPUS",
  ADD_CAMPUS: "ADD_CAMPUS",
  UPDATE_CAMPUS: "UPDATE_CAMPUS",
  DELETE_CAMPUS: "DELETE_CAMPUS",
  COUNTDUX: "COUNTDUX",
  MIGRATEDUX: "MIGRATEDUX",
  QUACKONE: "QUACKONE"
};
