export default {

    GET_CAMPUS : 'GET_CAMPUS',
	GET_ALL_CAMPUS : 'GET_ALL_CAMPUS',
	ADD_CAMPUS : 'ADD_CAMPUS',
	UPDATE_CAMPUS : 'UPDATE_CAMPUS',
	DELETE_CAMPUS : 'DELETE_CAMPUS',
	COUNTDUX : 'COUNTDUX',
}