export default { GET_TERMINATOR : 'GET_TERMINATOR',
	GET_ALL_TERMINATOR : 'GET_ALL_TERMINATOR',
	ADD_TERMINATOR : 'ADD_TERMINATOR',
	UPDATE_TERMINATOR : 'UPDATE_TERMINATOR',
  DELETE_TERMINATOR : 'DELETE_TERMINATOR' }