export default {
	GET_GIT : 'GET_GIT',
	GET_ALL_GIT : 'GET_ALL_GIT',
	ADD_GIT : 'ADD_GIT',
	UPDATE_GIT : 'UPDATE_GIT',
	DELETE_GIT : 'DELETE_GIT'
	GET_BRANCH : 'GET_BRANCH',
	GET_ALL_BRANCH : 'GET_ALL_BRANCH',
	ADD_BRANCH : 'ADD_BRANCH',
	UPDATE_BRANCH : 'UPDATE_BRANCH',
	DELETE_BRANCH : 'DELETE_BRANCH'
}